export enum Role {
  Auditor = 'Auditor',
  Requestor = 'Requestor',
  Admin = 'Admin',
  Manager = 'Manager',
  Guest = 'Guest'
}
export enum GEN_AUDIT_STATE {
  AUDIT_REQUEST_INITIATED = 1,
  AUDIT_REQUEST_COMPLETED = 2,
  AUDIT_INITIATED = 3,
  AUDIT_COMPLETED = 4,
  AUDIT_CLOSURE_INIATED = 5,
  AUDIT_CLOSURE_COMPLETED = 6,
  AUDIT_CLOSED = 7
}
export enum REQUESTOR_AUDIT_STATE {
  REQUEST_FOR_AUDIT = 1,
  WAITING_FOR_AUDIOR_TO_ACCEPT_REJECT = 2,
  WAITING_FOR_AUDIT = 3,
  ACCEPT_REJECT_AUDIT = 5,
  WAITING_FOR_AUDIT_CLOSURE = 6,
  AUDIT_CLOSED = 7
}
export enum AUDITOR_AUDIT_STATE {
  WAITING_FOR_AUDIT_REQUEST = 1,
  ACCEPT_REJEC_AUDIT_REQUEST = 2,
  AUDIT_THE_CODE = 3,
  COMPLETE_AUDITT = 4,
  WAIT_FOR_TEAMLEAD_TO_ACCEPT_REJECT = 5,
  ACCET_REJECT_AUDIT_CHANGES = 6,
  AUDIT_CLOSED = 7
}
